version: "3.7"

services:
  php:
    image: lorisleiva/laravel-docker:7.3
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=80
    ports:
      - '80:80'
    networks:
      - backend
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
volumes:
  db-data:
networks:
  backend: