version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports:
      - 3000:3000  
  ngnix:
    image: nginx:1.17.9-alpine
    ports:
      - 80:80
    volumes:
      - ./.docker/ngnix/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node