version: "3.7"

services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 80:80

## Choose a database container (MySQL or PosgresSQL)

#   db:
#     image: mysql:8.0
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_USER: ${DB_USER}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - db-data:/var/lib/mysql
#       ## - ./migrations:/docker-entrypoint-initdb.d
#     ports:
#       - 3306:3306

#   db:
#     image: postgres:12.2-alpine
#     environment:
#       POSTGRES_DB: mailoo
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       PGDATA: /data/postgres
#     volumes:
#       - db-data:/data/postgres
#       ## - ./migrations:/docker-entrypoint-initdb.d
#     ports:
#       - 5432:5432


volumes:
  db-data:
