version: "3.7"

services:
  web:
    image: nginx:1.17.9-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./ngnix/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  php:
    image: php:7.3-fpm-alpine
    volumes:
      - ./:/var/www/html
    networks:
      - backend
networks:
  backend: